services:
  pssh-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pssh-node-1
    hostname: pssh-node-1
    environment:
      - TZ=UTC
      - USER_NAME=cluster
      - USER_PASSWORD=cluster
    ports:
      - "2231:22"
    networks:
      pssh-net:
        ipv4_address: 172.30.0.11

  pssh-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pssh-node-2
    hostname: pssh-node-2
    environment:
      - TZ=UTC
      - USER_NAME=cluster
      - USER_PASSWORD=cluster
    ports:
      - "2232:22"
    networks:
      pssh-net:
        ipv4_address: 172.30.0.12

  pssh-node-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pssh-node-3
    hostname: pssh-node-3
    environment:
      - TZ=UTC
      - USER_NAME=cluster
      - USER_PASSWORD=cluster
    ports:
      - "2233:22"
    networks:
      pssh-net:
        ipv4_address: 172.30.0.13

networks:
  pssh-net:
    name: pssh-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
